### ISSUE TITLE
Label is breaking even if there is enough space

### ISSUE THREAD

**Issue by padinko** [odyzeo/form-item#15]
![image](https://user-images.githubusercontent.com/12599001/75136001-89578280-56e3-11ea-9b0d-9384bf041839.png)

**Comment by LordZombi** [comment]
https://github.com/odyzeo/form-item/releases/tag/v2.3.5

- fixed in provided project

**Comment by padinko** [comment]
can display block be default?

**Comment by LordZombi** [comment]
Yeah, it should be. In v2.3.6 it is.
But in some projects we skip importing default styles and use own, so watch out for it please.
